const dimensionedScalar rateZero
(
    "rateZero", dimensionSet(0,0,-1,0,0), scalar(0)
);
const dimensionedScalar dimlessSMALL
(
    "dimlessSMALL", dimless, SMALL
);
const dimensionedScalar rateSMALL
(
    "rateSMALL", dimensionSet(0,0,-1,0,0), SMALL
);
const dimensionedScalar dimlessZero
(
    "dimlessZero", dimless, scalar(0)
);
const dimensionedScalar bZero
(
    "bZero", dimensionSet(0,1,-2,0,0), scalar(0)
);
const dimensionedScalar bSMALL
(
    "bSMALL", dimensionSet(0,1,-2,0,0), SMALL
);
const dimensionedScalar speedSMALL
(
    "speedSMALL", dimensionSet(0,1,-1,0,0), SMALL
);
const dimensionedScalar dbdtZero
(
    "dbdtZero", dimensionSet(0,1,-3,0,0), scalar(0)
);
const dimensionedScalar dbdtSMALL
(
    "dbdtSMALL", dimensionSet(0,1,-3,0,0), SMALL
);
const dimensionedScalar dbdzZero
(
    "dbdzZero", dimensionSet(0,0,-2,0,0), scalar(0)
);
const dimensionedScalar fluxZero
(
    "fluxZero", dimensionSet(0,3,-1,0,0), scalar(0)
);
const dimensionedScalar fluxChangeZero
(
    "fluxChangeZero", dimensionSet(0,3,-2,0,0), scalar(0)
);
const dimensionedScalar lengthZero
(
    "lengthZero", dimensionSet(0,1,0,0,0), scalar(0)
);

