const dimensionedScalar rateZero
(
    "rateZero", dimensionSet(0,0,-1,0,0), scalar(0)
);
const dimensionedScalar dimlessSMALL
(
    "dimlessSMALL", dimless, SMALL
);
const dimensionedScalar rateSMALL
(
    "rateSMALL", dimensionSet(0,0,-1,0,0), SMALL
);
const dimensionedScalar dimlessZero
(
    "dimlessZero", dimless, scalar(0)
);
const dimensionedScalar bZero
(
    "bZero", dimensionSet(0,1,-2,0,0), scalar(0)
);
const dimensionedScalar bSMALL
(
    "bSMALL", dimensionSet(0,1,-2,0,0), SMALL
);
const dimensionedScalar speedSMALL
(
    "speedSMALL", dimensionSet(0,1,-1,0,0), SMALL
);

// Minimum sigma for division
const scalar minSigmaDiv = SMALL;

